server:
  port: 8080

spring:
  application:
    name: lab2
  datasource:
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: Alexpozitiv2002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
